name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest;
    steps:
      - name: say hello
        run: echo "hello world"
      - name: run app1
        run: npm start
